### ISSUE TITLE
沒有demo

### ISSUE THREAD

**Issue by jacky8399** [MichaelRix/sprin9#1]
塊弄個 `MichaelRix.github.io`

**Comment by MichaelRix** [comment]
@jacky8399 其实是有michaelrix.github.io的

**Comment by MichaelRix** [comment]
michaelrix.github.io 早就被 del 了。

In fact，你可以 git clone 这个 repo，然后你就有本地 demo 了（确信）。

**Comment by jacky8399** [comment]
@MichaelRix 塊在dogs.nottres.com弄個demo
話說，_(Function f)可以欽定成document.addEventListener("DOMContentLoaded", f)，copy place一下jquery
